import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Sun, Battery, Home, Shield, Settings } from "lucide-react";

const cards = [
  {
    title: "Solar Battery Storage",
    icon: <Battery className="w-8 h-8 text-primary" />,
    images: ["/sbattery.png", "/sbattery4.png", "/sbattery2.png", "/sbattery3.png"],
    text: "Solar batteries are essential for storing energy generated by solar panels, allowing you to use that energy when the sun isn't shining. They provide backup power during outages and help maximize the efficiency of your solar energy system.",
    features: [
      "24/7 Power Availability",
      "Smart Energy Management",
      "Extended Battery Life",
      "Weather-Resistant Design",
      "Remote Monitoring",
      "Scalable Capacity"
    ],
    specifications: {
      capacity: "13.5 kWh - 40 kWh",
      warranty: "10 Years",
      efficiency: "90%+",
      installation: "Indoor/Outdoor"
    }
  },
  {
    title: "Professional Solar Installations",
    icon: <Home className="w-8 h-8 text-primary" />,
    images: ["/house.png", "/house2.png", "/house3.png"],
    text: "Our expert installation team ensures your solar system is perfectly configured for maximum efficiency and longevity. We handle everything from initial assessment to final setup.",
    features: [
      "Free Site Assessment",
      "Custom System Design",
      "Professional Installation",
      "Permit Management",
      "Utility Coordination",
      "Post-Installation Support"
    ],
    process: [
      "Initial Consultation",
      "Site Survey",
      "Custom Design",
      "Installation",
      "Inspection",
      "System Activation"
    ]
  },
  {
    title: "High-Efficiency Solar Panels",
    icon: <Sun className="w-8 h-8 text-primary" />,
    images: ["/Panel3.png", "/Panel4.png", "/Panel5.png", "/Panel6.png", "/Panel7.png"],
    text: "Our premium solar panels deliver industry-leading efficiency and durability. Each panel is rigorously tested and backed by comprehensive warranties.",
    features: [
      "High Conversion Efficiency",
      "Weather-Resistant",
      "Anti-Reflective Coating",
      "Extended Warranty",
      "Premium Materials",
      "Advanced Technology"
    ],
    specifications: {
      efficiency: "21.5%+",
      warranty: "25 Years",
      power: "400W-500W",
      type: "Monocrystalline"
    }
  }
];

const projectImages = [
  {
    id: 1,
    alt: "Solar Installation Project 1",
    description: "200kW Commercial Installation"
  },
  {
    id: 2,
    alt: "Solar Battery Storage System",
    description: "Residential Battery Backup Solution"
  },
  {
    id: 3,
    alt: "Commercial Solar Array",
    description: "Large Scale Commercial Project"
  },
  {
    id: 4,
    alt: "Residential Solar Installation",
    description: "Home Solar Power System"
  }
];

export default function Solar() {
  const [activeCard, setActiveCard] = useState(null);
  const [selectedImage, setSelectedImage] = useState(null);

  const handleToggle = (title) => {
    setActiveCard(activeCard === title ? null : title);
  };

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="w-full bg-gradient-to-br from-gray-50 to-white pt-28 pb-16 md:pt-36 md:pb-24">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
            <div className="order-2 md:order-1">
              <motion.h1 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-800 leading-tight"
              >
                <span className="text-green-600">Sustainable</span> Solar Energy Solutions
              </motion.h1>
              <motion.p 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="text-lg md:text-xl text-gray-600 mt-6"
              >
                Harnessing the power of the sun with state-of-the-art solar technology and expert installation services for a greener tomorrow.
              </motion.p>
              <motion.div 
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="mt-8 space-x-4"
              >
                <a 
                  href="#contact" 
                  className="inline-flex items-center px-6 py-3 bg-green-600 text-white font-medium rounded-md hover:bg-green-700 transition-colors duration-300"
                >
                  Get Started
                  <ArrowRight size={18} className="ml-2" />
                </a>
                <a 
                  href="#services" 
                  className="inline-flex items-center px-6 py-3 border border-green-600 text-green-600 font-medium rounded-md hover:bg-green-50 transition-colors duration-300"
                >
                  Our Services
                </a>
              </motion.div>
            </div>
            <div className="order-1 md:order-2 relative">
              <div className="relative h-64 md:h-auto overflow-hidden rounded-lg shadow-xl">
                <img 
                  src="/solar-hero.jpg" 
                  alt="Solar panel installation" 
                  className="w-full h-full object-cover transform hover:scale-105 transition-transform duration-700"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-green-900/50 to-transparent"></div>
              </div>
              <div className="absolute -bottom-6 -left-6 w-24 h-24 bg-green-600 rounded-full flex items-center justify-center text-white font-bold text-lg animate-pulse">
                25+ Years
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Services Section */}
      <section className="py-16 md:py-24 bg-white">
        <div className="container mx-auto px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-4">Our Solar Services</h2>
            <div className="w-24 h-1 bg-green-600 mx-auto mb-6"></div>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              We provide comprehensive solar solutions tailored to meet your energy needs and sustainability goals.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {[
              {
                icon: <Sun className="w-8 h-8 text-green-600" />,
                title: "Solar Installation",
                description: "Professional installation of high-efficiency solar panel systems."
              },
              {
                icon: <Battery className="w-8 h-8 text-green-600" />,
                title: "Battery Storage",
                description: "Advanced battery solutions for energy storage and backup power."
              },
              {
                icon: <Settings className="w-8 h-8 text-green-600" />,
                title: "System Maintenance",
                description: "Regular maintenance and monitoring of solar power systems."
              },
              {
                icon: <Shield className="w-8 h-8 text-green-600" />,
                title: "Energy Consulting",
                description: "Expert advice on solar solutions and energy optimization."
              }
            ].map((service, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="bg-white p-6 rounded-lg shadow-lg hover:shadow-xl border-t-4 border-green-600 transition-all duration-300 hover:-translate-y-2"
              >
                <div className="mb-4">{service.icon}</div>
                <h3 className="text-xl font-semibold text-gray-800 mb-3">{service.title}</h3>
                <p className="text-gray-600">{service.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Additional Features Section */}
      <section className="py-16 md:py-24 bg-gray-50">
        <div className="container mx-auto px-4 md:px-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-6">
                Why Choose Our Solar Solutions?
              </h2>
              <div className="space-y-4">
                {[
                  "High-efficiency solar panels",
                  "Expert installation team",
                  "25-year warranty",
                  "Smart monitoring systems",
                  "Energy storage solutions",
                  "Competitive pricing"
                ].map((feature, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="flex items-center space-x-3"
                  >
                    <ArrowRight className="w-5 h-5 text-green-600" />
                    <span className="text-gray-700">{feature}</span>
                  </motion.div>
                ))}
              </div>
            </div>
            <div className="grid grid-cols-2 gap-4">
              {[1, 2, 3, 4].map((item) => (
                <div key={item} className="rounded-lg overflow-hidden shadow-lg">
                  <img 
                    src={`/solar-feature-${item}.jpg`}
                    alt={`Solar feature ${item}`}
                    className="w-full h-48 object-cover"
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-16 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {cards.map((card) => (
              <motion.div
                key={card.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="bg-gray-50 rounded-xl shadow-lg overflow-hidden"
              >
                {/* Card Header */}
                <div className="p-6 bg-gradient-to-r from-primary to-primary/80 text-white">
                  <div className="flex items-center gap-4 mb-4">
                    {card.icon}
                    <h3 className="text-xl font-bold">{card.title}</h3>
                  </div>
                </div>

                {/* Image Gallery */}
                <div className="p-6">
                  <div className="grid grid-cols-2 gap-4">
                    {card.images.map((image, index) => (
                      <motion.img
                        key={index}
                        src={image}
                        alt={`${card.title} ${index + 1}`}
                        className="rounded-lg border-2 border-primary/20 w-full cursor-pointer"
                        whileHover={{ scale: 1.05 }}
                        onClick={() => setSelectedImage(image)}
                      />
                    ))}
                  </div>

                  {/* Expandable Content */}
                  <motion.div
                    initial={false}
                    animate={{ height: activeCard === card.title ? "auto" : 0 }}
                    className="overflow-hidden"
                  >
                    <div className="pt-6 space-y-4">
                      <p className="text-gray-600">{card.text}</p>
                      
                      {/* Features */}
                      <div>
                        <h4 className="font-semibold text-primary mb-2">Key Features</h4>
                        <ul className="grid grid-cols-2 gap-2">
                          {card.features.map((feature, index) => (
                            <li key={index} className="flex items-center gap-2 text-sm">
                              <Sun className="w-4 h-4 text-secondary" />
                              {feature}
                            </li>
                          ))}
                        </ul>
                      </div>

                      {/* Specifications or Process */}
                      {card.specifications && (
                        <div>
                          <h4 className="font-semibold text-primary mb-2">Specifications</h4>
                          <div className="grid grid-cols-2 gap-4 text-sm">
                            {Object.entries(card.specifications).map(([key, value]) => (
                              <div key={key} className="bg-white p-2 rounded">
                                <span className="font-medium">{key}: </span>
                                {value}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}

                      {card.process && (
                        <div>
                          <h4 className="font-semibold text-primary mb-2">Installation Process</h4>
                          <div className="flex flex-wrap gap-2">
                            {card.process.map((step, index) => (
                              <div key={index} className="flex items-center gap-1 text-sm">
                                <span className="bg-primary text-white rounded-full w-5 h-5 flex items-center justify-center">
                                  {index + 1}
                                </span>
                                {step}
                                {index < card.process.length - 1 && <ArrowRight className="w-4 h-4" />}
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  </motion.div>

                  <button 
                    onClick={() => handleToggle(card.title)} 
                    className="mt-6 text-primary font-semibold hover:text-secondary transition-colors flex items-center gap-2"
                  >
                    {activeCard === card.title ? "Show Less" : "Learn More"}
                    <ArrowRight className="w-4 h-4" />
                  </button>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Project Showcase Section */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Our Recent Projects</h2>
          
          <div className="relative overflow-hidden">
            <motion.div 
              className="flex gap-6"
              animate={{
                x: [-100, 0],
              }}
              transition={{
                duration: 20,
                repeat: Infinity,
                ease: "linear"
              }}
            >
              {projectImages.map((image) => (
                <motion.div
                  key={image.id}
                  className="min-w-[300px] bg-gray-50 rounded-lg overflow-hidden shadow-lg"
                  whileHover={{ scale: 1.05 }}
                  transition={{ duration: 0.3 }}
                >
                  <div className="h-48 bg-gray-200">
                    {/* Image placeholder - replace src later */}
                    <img
                      src="placeholder.jpg"
                      alt={image.alt}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  <div className="p-4">
                    <p className="text-lg font-semibold">{image.description}</p>
                  </div>
                </motion.div>
              ))}
            </motion.div>
          </div>
        </div>
      </section>
      {/* Image Modal */}
      {selectedImage && (
        <div 
          className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4"
          onClick={() => setSelectedImage(null)}
        >
          <motion.img
            initial={{ scale: 0.5, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            src={selectedImage}
            alt="Enlarged view"
            className="max-w-full max-h-[90vh] rounded-lg"
          />
        </div>
      )}
    </div>
  );
}
